services:
  - type: web
    name: liberal-web
    env: python
    region: oregon
    plan: free
    branch: main
    repo: https://github.com/caicedotobonjavier/liberal

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: liberal.settings.prod

      - key: SECRET_KEY
        sync: false

      - key: DEBUG
        value: False

      - key: ALLOWED_HOSTS
        value: liberal-web.onrender.com

      # ESTA VARIABLE VIENE AUTOM√ÅTICAMENTE DE LA BD
      - key: DATABASE_URL
        fromDatabase:
          name: liberal-db
          property: connectionString

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate --no-input

    startCommand: gunicorn liberal.wsgi --bind 0.0.0.0:$PORT --log-file -

databases:
  - name: liberal-db
    plan: free
    region: oregon